name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dynamic-run-portfolio1

      - name: Configure Docker for Artifact Registry (if needed)
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gcr.io/dynamic-run-portfolio1/dynamic-run-portfolio:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dynamic-run-portfolio \
            --image=gcr.io/dynamic-run-portfolio1/dynamic-run-portfolio:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated


            